server:
  port: 8080

spring:
  application:
    name: authentication-backend
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: icarodrx@gmail.com
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000
  type: Bearer

logging:
  level:
    org.springframework.transaction: TRACE
    org.hibernate.engine.transaction.internal: DEBUG
    org.hibernate.resource.transaction.backend.jdbc.internal: DEBUG
    org.hibernate.engine.jdbc.connections.internal.JdbcConnectionAccessImpl: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

app:
  frontend:
    url: http://localhost:5173